# Generated by Django 5.1.6 on 2025-03-01 11:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_analysisresult_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisresult',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='results',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='tool_times',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
